pub struct BuildingDefinition {
    pub building_type: &'static str,
    pub label: &'static str,
    pub width: i32,
    pub height: i32,
    pub cost: i32,
    pub allowed_area: Option<&'static str>,
    pub effect: &'static str,
    pub citizen_count: u16,
}

pub const BUILDINGS: &[BuildingDefinition] = &[
    BuildingDefinition {
        building_type: "busStop",
        label: "Bus Stop",
        width: 1,
        height: 1,
        cost: 2_000,
        allowed_area: None,
        effect: "busStop",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "busTerminal",
        label: "Bus Terminal",
        width: 3,
        height: 2,
        cost: 12_000,
        allowed_area: None,
        effect: "busTerminal",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "metroStation",
        label: "Metro Station",
        width: 1,
        height: 1,
        cost: 25_000,
        allowed_area: None,
        effect: "metroStation",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "smallHouse",
        label: "Small House",
        width: 2,
        height: 1,
        cost: 4_000,
        allowed_area: Some("residential"),
        effect: "housing",
        citizen_count: 4,
    },
    BuildingDefinition {
        building_type: "largeHouse",
        label: "Large House",
        width: 3,
        height: 2,
        cost: 10_000,
        allowed_area: Some("residential"),
        effect: "housing",
        citizen_count: 10,
    },
    BuildingDefinition {
        building_type: "supermarket",
        label: "Supermarket",
        width: 2,
        height: 2,
        cost: 8_000,
        allowed_area: Some("commercial"),
        effect: "destination",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "cinema",
        label: "Cinema",
        width: 3,
        height: 2,
        cost: 14_000,
        allowed_area: Some("commercial"),
        effect: "destination",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "factory",
        label: "Factory",
        width: 3,
        height: 2,
        cost: 16_000,
        allowed_area: Some("industrial"),
        effect: "destination",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "warehouse",
        label: "Warehouse",
        width: 3,
        height: 2,
        cost: 12_000,
        allowed_area: Some("industrial"),
        effect: "destination",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "officeTower",
        label: "Office Tower",
        width: 2,
        height: 2,
        cost: 18_000,
        allowed_area: Some("office"),
        effect: "destination",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "businessPark",
        label: "Business Park",
        width: 3,
        height: 2,
        cost: 15_000,
        allowed_area: Some("office"),
        effect: "destination",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "clinic",
        label: "Clinic",
        width: 2,
        height: 2,
        cost: 12_000,
        allowed_area: Some("civic"),
        effect: "destination",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "school",
        label: "School",
        width: 3,
        height: 2,
        cost: 18_000,
        allowed_area: Some("civic"),
        effect: "destination",
        citizen_count: 0,
    },
    BuildingDefinition {
        building_type: "parkPlaza",
        label: "Park Plaza",
        width: 2,
        height: 2,
        cost: 6_000,
        allowed_area: Some("park"),
        effect: "destination",
        citizen_count: 0,
    },
];

pub fn building_definition(building_type: &str) -> Option<&'static BuildingDefinition> {
    BUILDINGS
        .iter()
        .find(|definition| definition.building_type == building_type)
}
